export const LOGIN_GET_USER_LOGIN = 'LOGIN_GET_USER_LOGIN';

export const SUMMARY_GET_SUMMARY_REPORT = 'SUMMARY_GET_SUMMARY_REPORT';
export const SUMMARY_GET_REPORT_MONTHLY = 'SUMMARY_GET_REPORT_MONTHLY';
export const SUMMARY_GET_REPORT_CONTENT = 'SUMMARY_GET_REPORT_CONTENT';
export const SUMMARY_GET_REPORT_MONTHLY_CLEAR = 'SUMMARY_GET_REPORT_MONTHLY_CLEAR';

export const LEARNING_GET_LEARNING_LIST = 'LEARNING_GET_LEARNING_LIST';
export const LEARNING_GET_LEARNING_DETAIL = 'LEARNING_GET_LEARNING_DETAIL';
export const LEARNING_GET_LEARNING_RECORD = 'LEARNING_GET_LEARNING_RECORD';
export const LEARNING_GET_LEARNING_LIST_CLEAR = 'LEARNING_GET_LEARNING_LIST_CLEAR';

// 暑期报告相关 start
export const SUMMER_REPORT_GET_DETAIL = 'SUMMER_REPORT_GET_DETAIL'; //getSummerkPointList
export const SUMMER_REPORT_GET_POINTLIST = 'SUMMER_REPORT_GET_POINTLIST'; //getSummerkPointList
export const REPORT_PRE_SHARE = 'REPORT_PRE_SHARE'; //postPreShare
export const REPORT_GET_SHARE_CONTENT = 'REPORT_GET_SHARE_CONTENT';
// 暑期报告相关 end


export const GET_USER_INFO = 'GET_USER_INFO';

// 系统相关
export const SET_SYSTEM_INFO = 'SET_SYSTEM_INFO';